from app.schemas.agents import AgentManifest, HandoffPolicy, SkillPolicy


def _object_schema(title: str) -> dict[str, object]:
    return {"title": title, "type": "object", "additionalProperties": True}


AGENT_MANIFESTS: dict[str, AgentManifest] = {
    "supervisor": AgentManifest(
        agent_id="supervisor",
        goal="Route user intent, coordinate specialist agents, and keep the run focused on the user's career outcome.",
        success_criteria=[
            "Selects the next agent based on current state and available artifacts.",
            "Hands off with enough context for the target agent to act.",
            "Stops when the user-facing objective is complete or blocked.",
        ],
        input_schema=_object_schema("SupervisorInput"),
        output_schema=_object_schema("SupervisorOutput"),
        allowed_tools=[],
        skill_policy=SkillPolicy(default_skill_ids=["memory/context_compaction"]),
        handoff_policy=HandoffPolicy(
            allowed_targets=[
                "memory_manager",
                "profile",
                "job",
                "match",
                "planning",
                "training",
                "interview",
                "report",
            ]
        ),
        readable_artifact_kinds=[],
        writable_artifact_kinds=[],
        readable_memory_scopes=["profile", "preferences", "career_history", "artifacts"],
        writable_memory_scopes=[],
    ),
    "memory_manager": AgentManifest(
        agent_id="memory_manager",
        goal="Load, compact, and persist user memory needed by the current career workflow.",
        success_criteria=[
            "Retrieves relevant long-term memory for the active task.",
            "Writes durable memory updates only when they are useful for future runs.",
        ],
        input_schema=_object_schema("MemoryManagerInput"),
        output_schema=_object_schema("MemoryManagerOutput"),
        allowed_tools=["memory_read", "memory_write", "artifact_write"],
        skill_policy=SkillPolicy(default_skill_ids=["memory/long_term_write_policy", "memory/context_compaction"]),
        handoff_policy=HandoffPolicy(allowed_targets=["supervisor"]),
        readable_artifact_kinds=[],
        writable_artifact_kinds=["compaction_snapshot"],
        readable_memory_scopes=["profile", "preferences", "career_history", "artifacts"],
        writable_memory_scopes=["profile", "preferences", "career_history", "artifacts"],
    ),
    "profile": AgentManifest(
        agent_id="profile",
        goal="Build and maintain the user's career profile from resumes, conversation, and saved memory.",
        success_criteria=[
            "Extracts structured experience, skills, goals, and constraints.",
            "Saves a profile artifact suitable for downstream matching and planning.",
        ],
        input_schema=_object_schema("ProfileInput"),
        output_schema=_object_schema("ProfileOutput"),
        allowed_tools=["artifact_read", "artifact_write", "memory_read"],
        skill_policy=SkillPolicy(default_skill_ids=["profile/resume_parsing", "profile/evidence_chain"]),
        handoff_policy=HandoffPolicy(allowed_targets=["job", "match", "memory_manager"]),
        readable_artifact_kinds=["profile"],
        writable_artifact_kinds=["profile"],
        readable_memory_scopes=["profile", "career_history", "preferences"],
        writable_memory_scopes=[],
    ),
    "job": AgentManifest(
        agent_id="job",
        goal="Analyze target roles or job descriptions into structured requirements.",
        success_criteria=[
            "Identifies responsibilities, qualifications, signals, and risks.",
            "Saves a job analysis artifact for matching and preparation.",
        ],
        input_schema=_object_schema("JobInput"),
        output_schema=_object_schema("JobOutput"),
        allowed_tools=["artifact_read", "artifact_write"],
        skill_policy=SkillPolicy(default_skill_ids=["job/jd_analysis", "job/agent_developer_role"]),
        handoff_policy=HandoffPolicy(allowed_targets=["match", "memory_manager"]),
        readable_artifact_kinds=["profile", "job_analysis"],
        writable_artifact_kinds=["job_analysis"],
        readable_memory_scopes=["profile", "career_history", "preferences"],
        writable_memory_scopes=[],
    ),
    "match": AgentManifest(
        agent_id="match",
        goal="Compare the user's profile against target job requirements and explain fit.",
        success_criteria=[
            "Scores strengths, gaps, and role alignment with evidence.",
            "Saves a match artifact that planning and reporting can reuse.",
        ],
        input_schema=_object_schema("MatchInput"),
        output_schema=_object_schema("MatchOutput"),
        allowed_tools=["artifact_read", "artifact_write", "memory_read"],
        skill_policy=SkillPolicy(default_skill_ids=["match/match_scoring_rubric", "match/gap_diagnosis"]),
        handoff_policy=HandoffPolicy(allowed_targets=["planning", "training", "memory_manager"]),
        readable_artifact_kinds=["profile", "job_analysis", "match"],
        writable_artifact_kinds=["match"],
        readable_memory_scopes=["profile", "career_history", "preferences"],
        writable_memory_scopes=[],
    ),
    "planning": AgentManifest(
        agent_id="planning",
        goal="Create a concrete career or application plan from profile, job, and match artifacts.",
        success_criteria=[
            "Prioritizes actions by impact, time, and user constraints.",
            "Saves a plan artifact with milestones and next steps.",
        ],
        input_schema=_object_schema("PlanningInput"),
        output_schema=_object_schema("PlanningOutput"),
        allowed_tools=["artifact_read", "artifact_write", "memory_read"],
        skill_policy=SkillPolicy(default_skill_ids=["planning/career_path_planning", "planning/three_month_plan"]),
        handoff_policy=HandoffPolicy(allowed_targets=["training", "interview", "report", "memory_manager"]),
        readable_artifact_kinds=["profile", "job_analysis", "match", "plan"],
        writable_artifact_kinds=["plan"],
        readable_memory_scopes=["profile", "preferences", "career_history"],
        writable_memory_scopes=[],
    ),
    "training": AgentManifest(
        agent_id="training",
        goal="Generate focused practice tasks or learning drills for the user's target gaps.",
        success_criteria=[
            "Creates exercises tied to the plan or match gaps.",
            "Saves training results or recommended practice artifacts.",
        ],
        input_schema=_object_schema("TrainingInput"),
        output_schema=_object_schema("TrainingOutput"),
        allowed_tools=["artifact_read", "artifact_write"],
        skill_policy=SkillPolicy(
            default_skill_ids=["training/workplace_task_generation", "training/submission_scoring"]
        ),
        handoff_policy=HandoffPolicy(allowed_targets=["interview", "report", "memory_manager"]),
        readable_artifact_kinds=["profile", "job_analysis", "match", "plan", "training_result"],
        writable_artifact_kinds=["training_result"],
        readable_memory_scopes=["profile", "preferences"],
        writable_memory_scopes=[],
    ),
    "interview": AgentManifest(
        agent_id="interview",
        goal="Prepare interview strategy, questions, and feedback for a target role.",
        success_criteria=[
            "Produces role-specific interview prompts and answer guidance.",
            "Saves an interview summary artifact with feedback and next steps.",
        ],
        input_schema=_object_schema("InterviewInput"),
        output_schema=_object_schema("InterviewOutput"),
        allowed_tools=["artifact_read", "artifact_write", "memory_read"],
        skill_policy=SkillPolicy(default_skill_ids=["interview/mock_interview_flow", "interview/answer_scoring"]),
        handoff_policy=HandoffPolicy(allowed_targets=["report", "memory_manager"]),
        readable_artifact_kinds=[
            "profile",
            "job_analysis",
            "match",
            "plan",
            "training_result",
            "interview_summary",
        ],
        writable_artifact_kinds=["interview_summary"],
        readable_memory_scopes=["profile", "career_history", "preferences"],
        writable_memory_scopes=[],
    ),
    "report": AgentManifest(
        agent_id="report",
        goal="Assemble user-facing summaries, recommendations, and final reports from run artifacts.",
        success_criteria=[
            "Synthesizes relevant artifacts into a clear user-facing report.",
            "Preserves artifact references used to produce the report.",
        ],
        input_schema=_object_schema("ReportInput"),
        output_schema=_object_schema("ReportOutput"),
        allowed_tools=["artifact_read", "artifact_write"],
        skill_policy=SkillPolicy(default_skill_ids=["report/markdown_report"]),
        handoff_policy=HandoffPolicy(allowed_targets=["memory_manager"]),
        readable_artifact_kinds=[
            "profile",
            "job_analysis",
            "match",
            "plan",
            "training_result",
            "interview_summary",
            "report",
        ],
        writable_artifact_kinds=["report"],
        readable_memory_scopes=["profile", "career_history", "preferences", "artifacts"],
        writable_memory_scopes=[],
    ),
}
